spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cyunyaotai
    url: jdbc:mysql://172.81.245.195:3306/cyunyaotai
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: 443
  servlet:
    context-path: /drug

ip: 172.81.245.195

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 172.81.245.195:22122
  web-server-url: http://${ip}:8888/


server.ssl.key-store: classpath:cauliflowerlucky.com.jks
server.ssl.key-store-password: w19jmt0626990
server.ssl.key-store-type: JKS

